-- Supabase table used by the Creatorverse React app.
create table if not exists creators (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  name text not null,
  url text not null,
  description text not null,
  "imageURL" text
);

alter table creators enable row level security;

-- These policies keep the prework app simple: public read/write access.
create policy "Public creators are viewable"
on creators for select
using (true);

create policy "Anyone can add creators"
on creators for insert
with check (true);

create policy "Anyone can update creators"
on creators for update
using (true);

create policy "Anyone can delete creators"
on creators for delete
using (true);
